### ISSUE TITLE
traefik support is not complete

### ISSUE THREAD

**Issue by progressify** [Hendrik44/infinitewp-docker#1]
Hi I think the traefik support is not complete.
I receive a series of errors when I try to use your project.

Are you still to maintaining this project?

**Comment by Hendrik44** [comment]
Hi sry that it took quite a while to get an answer. I updated now the repo and it is now working again. Because traefik significantly changed the syntax and it was written for traefik 1.x it failed. As workaround for now, until it is not updated to work with 2.x, I set it to a fixed and latest 1.x traefik version.

**Comment by Hendrik44** [comment]
If you still have an issue please reopen the issue
